/-
Copyright (c) 2026 CompElliptic Contributors. All rights reserved.
Released under the Apache License, Version 2.0, or the MIT license, at your option,
as described in the files LICENSE-APACHE and LICENSE-MIT.
Authors: Daira-Emma Hopwood
-/
import CompPoly.Fields.PrattCertificate

/-!
# The Jubjub scalar prime field

`JUBJUB_SCALAR_CARD` is `ℓ`, the order of the prime-order subgroup of the Jubjub curve — the scalar
field of the Sapling value commitment. The Jubjub curve has cofactor 8, so its full order is
`8 · ℓ`; `ℓ` itself is the prime the value commitment works over. We give `ℓ` a Lucas/Pratt primality
certificate, following the pattern of `CompElliptic.Fields.Pasta`; the certificate was generated by
`scripts/gen_jubjub.py` from the factorization of `ℓ - 1` (PARI/GP). The Jubjub curve itself and its
base field (the BLS12-381 scalar field) are not defined here.
-/

namespace CompElliptic.Fields.Jubjub

-- Jubjub scalar field ℓ (the prime-order subgroup order).
@[reducible] def JUBJUB_SCALAR_CARD : Nat := 0xe7db4ea6533afa906673b0101343b00a6682093ccc81082d0970e5ed6f72cb7

abbrev JubjubScalarField := ZMod JUBJUB_SCALAR_CARD

theorem JUBJUB_SCALAR_is_prime : Nat.Prime JUBJUB_SCALAR_CARD := by
  unfold JUBJUB_SCALAR_CARD
  refine PrattCertificate'.out (p := 6554484396890773809930967563523245729705921265872317281365359162392183254199) ⟨6, (by reduce_mod_char), ?_⟩
  refine .split [2, 3, 12281, 1710050753150114629, 203928654140967434528233, 255074062430788457494141376149] (fun r hr => ?_) (by norm_num)
  simp at hr
  rcases hr with hr | hr | hr | hr | hr | hr
  all_goals rw [hr]
  · exact .prime 2 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
  · exact .prime 3 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
  · exact .prime 12281 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
  · refine .prime 1710050753150114629 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
    refine PrattCertificate'.out (p := 1710050753150114629) ⟨6, (by reduce_mod_char), ?_⟩
    refine .split [2 ^ 2, 3, 11, 12954929948106929] (fun r hr => ?_) (by norm_num)
    simp at hr
    rcases hr with hr | hr | hr | hr
    all_goals rw [hr]
    · exact .prime 2 2 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 3 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 11 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · refine .prime 12954929948106929 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
      refine PrattCertificate'.out (p := 12954929948106929) ⟨3, (by reduce_mod_char), ?_⟩
      refine .split [2 ^ 4, 23, 35203613989421] (fun r hr => ?_) (by norm_num)
      simp at hr
      rcases hr with hr | hr | hr
      all_goals rw [hr]
      · exact .prime 2 4 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · exact .prime 23 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · refine .prime 35203613989421 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
        refine PrattCertificate'.out (p := 35203613989421) ⟨2, (by reduce_mod_char), ?_⟩
        refine .split [2 ^ 2, 5, 1699, 1036009829] (fun r hr => ?_) (by norm_num)
        simp at hr
        rcases hr with hr | hr | hr | hr
        all_goals rw [hr]
        · exact .prime 2 2 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 5 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 1699 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · refine .prime 1036009829 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
          refine PrattCertificate'.out (p := 1036009829) ⟨2, (by reduce_mod_char), ?_⟩
          refine .split [2 ^ 2, 7, 499, 74149] (fun r hr => ?_) (by norm_num)
          simp at hr
          rcases hr with hr | hr | hr | hr
          all_goals rw [hr]
          · exact .prime 2 2 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
          · exact .prime 7 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
          · exact .prime 499 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
          · exact .prime 74149 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
  · refine .prime 203928654140967434528233 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
    refine PrattCertificate'.out (p := 203928654140967434528233) ⟨5, (by reduce_mod_char), ?_⟩
    refine .split [2 ^ 3, 3 ^ 2, 6566909, 431305263804409] (fun r hr => ?_) (by norm_num)
    simp at hr
    rcases hr with hr | hr | hr | hr
    all_goals rw [hr]
    · exact .prime 2 3 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 3 2 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 6566909 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · refine .prime 431305263804409 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
      refine PrattCertificate'.out (p := 431305263804409) ⟨13, (by reduce_mod_char), ?_⟩
      refine .split [2 ^ 3, 3, 7, 2567293236931] (fun r hr => ?_) (by norm_num)
      simp at hr
      rcases hr with hr | hr | hr | hr
      all_goals rw [hr]
      · exact .prime 2 3 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · exact .prime 3 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · exact .prime 7 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · refine .prime 2567293236931 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
        refine PrattCertificate'.out (p := 2567293236931) ⟨2, (by reduce_mod_char), ?_⟩
        refine .split [2, 3, 5, 457, 187256983] (fun r hr => ?_) (by norm_num)
        simp at hr
        rcases hr with hr | hr | hr | hr | hr
        all_goals rw [hr]
        · exact .prime 2 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 3 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 5 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 457 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 187256983 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
  · refine .prime 255074062430788457494141376149 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
    refine PrattCertificate'.out (p := 255074062430788457494141376149) ⟨2, (by reduce_mod_char), ?_⟩
    refine .split [2 ^ 2, 3, 311, 5521, 19861, 623312455501769069] (fun r hr => ?_) (by norm_num)
    simp at hr
    rcases hr with hr | hr | hr | hr | hr | hr
    all_goals rw [hr]
    · exact .prime 2 2 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 3 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 311 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 5521 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · exact .prime 19861 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
    · refine .prime 623312455501769069 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
      refine PrattCertificate'.out (p := 623312455501769069) ⟨2, (by reduce_mod_char), ?_⟩
      refine .split [2 ^ 2, 7, 1361, 16356472538621] (fun r hr => ?_) (by norm_num)
      simp at hr
      rcases hr with hr | hr | hr | hr
      all_goals rw [hr]
      · exact .prime 2 2 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · exact .prime 7 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · exact .prime 1361 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
      · refine .prime 16356472538621 1 _ ?_ (by reduce_mod_char; decide) (by norm_num)
        refine PrattCertificate'.out (p := 16356472538621) ⟨2, (by reduce_mod_char), ?_⟩
        refine .split [2 ^ 2, 5, 23, 62701, 567097] (fun r hr => ?_) (by norm_num)
        simp at hr
        rcases hr with hr | hr | hr | hr | hr
        all_goals rw [hr]
        · exact .prime 2 2 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 5 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 23 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 62701 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)
        · exact .prime 567097 1 _ (by pratt) (by reduce_mod_char; decide) (by norm_num)

instance : Fact (Nat.Prime JUBJUB_SCALAR_CARD) := ⟨JUBJUB_SCALAR_is_prime⟩
instance : Field JubjubScalarField := ZMod.instField JUBJUB_SCALAR_CARD

end CompElliptic.Fields.Jubjub
