#!/usr/bin/env python3
# Copyright (c) 2026 CompElliptic Contributors. All rights reserved.
# Released under the Apache License, Version 2.0, or the MIT license, at your option,
# as described in the files LICENSE-APACHE and LICENSE-MIT.
# Authors: Daira-Emma Hopwood
"""
Generate `CompElliptic/Fields/Jubjub.lean`: the Jubjub scalar prime field `ℓ`, the order of the
prime-order subgroup of the Jubjub curve and the scalar field of the Sapling value commitment,
with a Lucas/Pratt primality certificate. The certificate machinery (factorization and
primitive-root search via PARI/GP, recursive certificate emission) is in `pratt.py`.

The Jubjub curve itself and its base field (the BLS12-381 scalar field) are not defined here; only
the scalar field cardinality is, which is what the Sapling value-balance argument needs.

Usage: run from the project root and write the result to the field file:
    python3 scripts/gen_jubjub.py > CompElliptic/Fields/Jubjub.lean
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pratt import field_block

# Jubjub scalar field ℓ (the prime-order subgroup order); see https://github.com/zkcrypto/jubjub.
L = 0x0e7db4ea6533afa906673b0101343b00a6682093ccc81082d0970e5ed6f72cb7

HEADER = """\
/-
Copyright (c) 2026 CompElliptic Contributors. All rights reserved.
Released under the Apache License, Version 2.0, or the MIT license, at your option,
as described in the files LICENSE-APACHE and LICENSE-MIT.
Authors: Daira-Emma Hopwood
-/
import CompPoly.Fields.PrattCertificate

/-!
# The Jubjub scalar prime field

`JUBJUB_SCALAR_CARD` is `ℓ`, the order of the prime-order subgroup of the Jubjub curve — the scalar
field of the Sapling value commitment. The Jubjub curve has cofactor 8, so its full order is
`8 · ℓ`; `ℓ` itself is the prime the value commitment works over. We give `ℓ` a Lucas/Pratt primality
certificate, following the pattern of `CompElliptic.Fields.Pasta`; the certificate was generated by
`scripts/gen_jubjub.py` from the factorization of `ℓ - 1` (PARI/GP). The Jubjub curve itself and its
base field (the BLS12-381 scalar field) are not defined here.
-/

namespace CompElliptic.Fields.Jubjub
"""

FOOTER = """\

end CompElliptic.Fields.Jubjub
"""


if __name__ == "__main__":
    out = HEADER
    out += field_block("JUBJUB_SCALAR", L, "JubjubScalarField",
                       "Jubjub scalar field ℓ (the prime-order subgroup order).")
    out += FOOTER
    print(out, end="")
