#!/usr/bin/env python3
# Copyright (c) 2026 CompElliptic Contributors. All rights reserved.
# Released under the Apache License, Version 2.0, or the MIT license, at your option,
# as described in the files LICENSE-APACHE and LICENSE-MIT.
# Authors: Daira-Emma Hopwood
"""
Generate `CompElliptic/Fields/Pasta.lean`: the Pallas/Vesta base and scalar prime fields, with
Lucas/Pratt primality certificates. The certificate machinery (factorization and primitive-root
search via PARI/GP, recursive certificate emission) is in `pratt.py`.

Usage: run from the project root and write the result to the field file:
    python3 scripts/gen_pasta.py > CompElliptic/Fields/Pasta.lean
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pratt import field_block

P = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001  # Pallas base
Q = 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001  # Pallas scalar (= Vesta base)

HEADER = """\
/-
Copyright (c) 2026 CompElliptic Contributors. All rights reserved.
Released under the Apache License, Version 2.0, or the MIT license, at your option,
as described in the files LICENSE-APACHE and LICENSE-MIT.
Authors: Daira-Emma Hopwood
-/
import CompPoly.Fields.PrattCertificate

/-!
# The Pasta (Pallas / Vesta) base and scalar prime fields

The Pallas and Vesta curves form a 2-cycle: the base field of one is the scalar field of the
other. We define the two underlying primes `p` (Pallas base = Vesta scalar) and `q` (Pallas
scalar = Vesta base), each with a Lucas/Pratt primality certificate, following the pattern of
`CompPoly.Fields.Secp256k1`. Certificates were generated by `scripts/gen_pasta.py` from the
factorizations of `p-1` and `q-1` (PARI/GP); see also https://github.com/zcash/pasta.
-/

namespace CompElliptic.Fields.Pasta
"""

FOOTER = """\

/-- Vesta base field = Pallas scalar field. -/
abbrev VestaBaseField := PallasScalarField
/-- Vesta scalar field = Pallas base field. -/
abbrev VestaScalarField := PallasBaseField

end CompElliptic.Fields.Pasta
"""


if __name__ == "__main__":
    out = HEADER
    out += field_block("PALLAS_BASE", P, "PallasBaseField",
                       "Pallas base field p (= Vesta scalar field).")
    out += field_block("PALLAS_SCALAR", Q, "PallasScalarField",
                       "Pallas scalar field q (= Vesta base field).")
    out += FOOTER
    print(out, end="")
