#!/usr/bin/env python3
# Copyright (c) 2026 CompElliptic Contributors. All rights reserved.
# Released under the Apache License, Version 2.0, or the MIT license, at your option,
# as described in the files LICENSE-APACHE and LICENSE-MIT.
# Authors: Daira-Emma Hopwood
"""
Generate `CompElliptic/Fields/Pasta.lean`: the Pallas/Vesta base and scalar prime fields, with
Lucas/Pratt primality certificates. The certificate machinery (factorization and primitive-root
search via PARI/GP, recursive certificate emission) is in `pratt.py`.

Usage: run from the project root and write the result to the field file:
    python3 scripts/gen_pasta.py > CompElliptic/Fields/Pasta.lean
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pratt import field_block

P = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001  # Pallas base
Q = 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001  # Pallas scalar (= Vesta base)

HEADER = """\
/-
Copyright (c) 2026 CompElliptic Contributors. All rights reserved.
Released under the Apache License, Version 2.0, or the MIT license, at your option,
as described in the files LICENSE-APACHE and LICENSE-MIT.
Authors: Daira-Emma Hopwood
-/
import CompPoly.Fields.PrattCertificate
import CompElliptic.Fields.Sqrt

/-!
# The Pasta (Pallas / Vesta) base and scalar prime fields

The Pallas and Vesta curves form a 2-cycle: the base field of one is the scalar field of the
other. We define the two underlying primes `p` (Pallas base = Vesta scalar) and `q` (Pallas
scalar = Vesta base), each with a Lucas/Pratt primality certificate, following the pattern of
`CompPoly.Fields.Secp256k1`. Certificates were generated by `scripts/gen_pasta.py` from the
factorizations of `p-1` and `q-1` (PARI/GP); see also https://github.com/zcash/pasta.
-/

namespace CompElliptic.Fields.Pasta
"""

FOOTER = """\

/-- Tonelli–Shanks data for the Pallas base field `𝔽ₚ`: `p-1 = 2^32 · T`, with `rootOfUnity = 5ᵀ`
(`pallas.py`). -/
def pallasBase : TonelliShanks Fp where
  twoAdicity := 32
  oddPart := 0x40000000000000000000000000000000224698fc094cf91b992d30ed
  rootOfUnity := 0x2bce74deac30ebda362120830561f81aea322bf2b7bb7584bdad6fabd87ea32f

-- `√4` squares back to `4`; `√5 = none` (5 is a non-residue, cf. `Pallas.five_not_isSquare`).
example : (pallasBase.sqrt? 4).map (· ^ 2) = some 4 := by native_decide
example : pallasBase.sqrt? 5 = none := by native_decide
-- `√((-1)³ + 5) = √4`: the `y` of the test point `G = (-1, 2)`.
example : (pallasBase.sqrt? ((-1 : Fp)^3 + 5)).map (· ^ 2) = some 4 := by native_decide

/-- Tonelli–Shanks data for the Vesta base field `𝔽_q` (`= Fq`): `q-1 = 2^32 · T`,
with `rootOfUnity = 5ᵀ` (`vesta.py`). -/
def vestaBase : TonelliShanks Fq where
  twoAdicity := 32
  oddPart := 0x40000000000000000000000000000000224698fc0994a8dd8c46eb21
  rootOfUnity := 0x2de6a9b8746d3f589e5c4dfd492ae26e9bb97ea3c106f049a70e2c1102b6d05f

-- `√4` squares back to `4`; `√5 = none` (5 is a non-residue, cf. `Vesta.five_not_isSquare`).
example : (vestaBase.sqrt? 4).map (· ^ 2) = some 4 := by native_decide
example : vestaBase.sqrt? 5 = none := by native_decide
-- `√((-1)³ + 5) = √4`: the `y` of the test point `G = (-1, 2)`.
example : (vestaBase.sqrt? ((-1 : Fq)^3 + 5)).map (· ^ 2) = some 4 := by native_decide

end CompElliptic.Fields.Pasta
"""


if __name__ == "__main__":
    out = HEADER
    out += field_block("PALLAS_BASE", P, "Fp",
                       "Pallas base field p (= Vesta scalar field).",
                       fielddoc="The Pallas base field `𝔽ₚ` — also the Vesta scalar field "
                                "(the Pasta cycle).")
    out += field_block("PALLAS_SCALAR", Q, "Fq",
                       "Pallas scalar field q (= Vesta base field).",
                       fielddoc="The Pallas scalar field `𝔽_q` — also the Vesta base field "
                                "(the Pasta cycle).")
    out += FOOTER
    print(out, end="")
